https://keras.io/getting-started/functional-api-guide/

# Sequential API

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(3, input_dim=4, activation='softmax'))

# Functional API

## Fully-connected FFNN

In [2]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

In [3]:
inputs = Input(shape=(10,))

In [4]:
inputs = Input(shape=(10,))
hidden1 = Dense(64, activation='relu')(inputs)  # <- 새로 추가
hidden2 = Dense(64, activation='relu')(hidden1) # <- 새로 추가
output = Dense(1, activation='sigmoid')(hidden2) # <- 새로 추가

In [5]:
model = Model(inputs=inputs, outputs=output) # <- 새로 추가

In [10]:
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [7]:
inputs = Input(shape=(10,))
x = Dense(8, activation="relu")(inputs)
x = Dense(4, activation="relu")(x)
x = Dense(1, activation="linear")(x)
model = Model(inputs, x)

In [9]:
import pydot
import graphviz
from tensorflow import keras
keras.utils.plot_model(model, to_file='model.png')

('You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) ', 'for plot_model/model_to_dot to work.')


## Linear Regression

In [12]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras import optimizers
from tensorflow.keras.models import Model
X = [1, 2, 3, 4, 5, 6, 7, 8, 9] # 공부하는 시간
y = [11, 22, 33, 44, 53, 66, 77, 87, 95] # 각 공부하는 시간에 맵핑되는 성적

inputs = Input(shape=(1,))
output = Dense(1, activation='linear')(inputs)
linear_model = Model(inputs, output)

sgd = optimizers.SGD(lr=0.01)

linear_model.compile(optimizer=sgd, loss='mse', metrics=['mse'])
linear_model.fit(X, y, epochs=300)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


Epoch 1/300
1/1 [==============================] - 0s 201ms/step - loss: 2633.7476 - mse: 2633.7476
Epoch 2/300
1/1 [==============================] - 0s 3ms/step - loss: 325.0599 - mse: 325.0599
Epoch 3/300
1/1 [==============================] - 0s 3ms/step - loss: 40.9927 - mse: 40.9927
Epoch 4/300
1/1 [==============================] - 0s 3ms/step - loss: 6.0398 - mse: 6.0398
Epoch 5/300
1/1 [==============================] - 0s 3ms/step - loss: 1.7386 - mse: 1.7386
Epoch 6/300
1/1 [==============================] - 0s 3ms/step - loss: 1.2088 - mse: 1.2088
Epoch 7/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1431 - mse: 1.1431
Epoch 8/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1345 - mse: 1.1345
Epoch 9/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1329 - mse: 1.1329
Epoch 10/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1322 - mse: 1.1322
Epoch 11/300
1/1 [==============================] - 0s 3ms/step -

1/1 [==============================] - 0s 4ms/step - loss: 1.0976 - mse: 1.0976
Epoch 90/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0973 - mse: 1.0973
Epoch 91/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0970 - mse: 1.0970
Epoch 92/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0967 - mse: 1.0967
Epoch 93/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0964 - mse: 1.0964
Epoch 94/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0961 - mse: 1.0961
Epoch 95/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0958 - mse: 1.0958
Epoch 96/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0955 - mse: 1.0955
Epoch 97/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0952 - mse: 1.0952
Epoch 98/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0949 - mse: 1.0949
Epoch 99/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0946 - ms

1/1 [==============================] - 0s 3ms/step - loss: 1.0689 - mse: 1.0689
Epoch 264/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0688 - mse: 1.0688
Epoch 265/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0687 - mse: 1.0687
Epoch 266/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0687 - mse: 1.0687
Epoch 267/300
1/1 [==============================] - 0s 4ms/step - loss: 1.0686 - mse: 1.0686
Epoch 268/300
1/1 [==============================] - 0s 5ms/step - loss: 1.0685 - mse: 1.0685
Epoch 269/300
1/1 [==============================] - 0s 4ms/step - loss: 1.0684 - mse: 1.0684
Epoch 270/300
1/1 [==============================] - 0s 4ms/step - loss: 1.0684 - mse: 1.0684
Epoch 271/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0683 - mse: 1.0683
Epoch 272/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0682 - mse: 1.0682
Epoch 273/300
1/1 [==============================] - 0s 2ms/step - loss: 1

In [14]:
linear_model.predict([9])

array([[96.879456]], dtype=float32)

## Logistic Regression

In [21]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

inputs = Input(shape=(1,))
output = Dense(1, activation='sigmoid')(inputs)
logistic_model = Model(inputs, output)

In [22]:
import numpy as np
x = np.array([-50, -40, -30, -20, -10, -5, 0, 5, 10, 20, 30, 40, 50])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]) # 숫자 10부터 1

In [23]:
sgd = optimizers.SGD(lr=0.01)

logistic_model.compile(optimizer=sgd, loss='binary_crossentropy', metrics=['binary_accuracy'])
logistic_model.fit(x, y, epochs=300)

Epoch 1/300
1/1 [==============================] - 0s 148ms/step - loss: 30.9816 - binary_accuracy: 0.1538
Epoch 2/300
1/1 [==============================] - 0s 952us/step - loss: 25.4778 - binary_accuracy: 0.1538
Epoch 3/300
1/1 [==============================] - 0s 2ms/step - loss: 19.9755 - binary_accuracy: 0.1538
Epoch 4/300
1/1 [==============================] - 0s 2ms/step - loss: 14.4787 - binary_accuracy: 0.1538
Epoch 5/300
1/1 [==============================] - 0s 2ms/step - loss: 9.0004 - binary_accuracy: 0.1538
Epoch 6/300
1/1 [==============================] - 0s 1000us/step - loss: 3.6051 - binary_accuracy: 0.1538
Epoch 7/300
1/1 [==============================] - 0s 2ms/step - loss: 0.2701 - binary_accuracy: 0.9231
Epoch 8/300
1/1 [==============================] - 0s 1ms/step - loss: 0.2464 - binary_accuracy: 0.9231
Epoch 9/300
1/1 [==============================] - 0s 932us/step - loss: 0.2347 - binary_accuracy: 0.9231
Epoch 10/300
1/1 [==============================] -

1/1 [==============================] - 0s 1ms/step - loss: 0.1819 - binary_accuracy: 0.9231
Epoch 155/300
1/1 [==============================] - 0s 2ms/step - loss: 0.1818 - binary_accuracy: 0.9231
Epoch 156/300
1/1 [==============================] - 0s 999us/step - loss: 0.1817 - binary_accuracy: 0.9231
Epoch 157/300
1/1 [==============================] - 0s 999us/step - loss: 0.1816 - binary_accuracy: 0.9231
Epoch 158/300
1/1 [==============================] - 0s 1ms/step - loss: 0.1815 - binary_accuracy: 0.9231
Epoch 159/300
1/1 [==============================] - 0s 2ms/step - loss: 0.1814 - binary_accuracy: 0.9231
Epoch 160/300
1/1 [==============================] - 0s 2ms/step - loss: 0.1813 - binary_accuracy: 0.9231
Epoch 161/300
1/1 [==============================] - 0s 2ms/step - loss: 0.1812 - binary_accuracy: 0.9231
Epoch 162/300
1/1 [==============================] - 0s 998us/step - loss: 0.1810 - binary_accuracy: 0.9231
Epoch 163/300
1/1 [==============================] - 0

In [26]:
print(logistic_model.predict([1, 2, 3, 4, 4.5]))
print(logistic_model.predict([11, 21, 31, 41, 500]))

[[0.47742158]
 [0.5335611 ]
 [0.58886325]
 [0.64200795]
 [0.66741145]]
[[0.89639926]
 [0.9879439 ]
 [0.99871314]
 [0.9998639 ]
 [1.        ]]


## Model that accepts multiple inputs

In [27]:
from tensorflow.keras.layers import Input, Dense, concatenate
from tensorflow.keras.models import Model

# 두 개의 입력층을 정의
inputA = Input(shape=(64,))
inputB = Input(shape=(128,))

# 첫번째 입력층으로부터 분기되어 진행되는 인공 신경망을 정의
x = Dense(16, activation="relu")(inputA)
x = Dense(8, activation="relu")(x)
x = Model(inputs=inputA, outputs=x)

# 두번째 입력층으로부터 분기되어 진행되는 인공 신경망을 정의
y = Dense(64, activation="relu")(inputB)
y = Dense(32, activation="relu")(y)
y = Dense(8, activation="relu")(y)
y = Model(inputs=inputB, outputs=y)

# 두개의 인공 신경망의 출력을 연결(concatenate)
result = concatenate([x.output, y.output])

z = Dense(2, activation="relu")(result)
z = Dense(1, activation="linear")(z)

model = Model(inputs=[x.input, y.input], outputs=z)

## RNN

In [28]:
from tensorflow.keras.layers import Input, Dense, LSTM
from tensorflow.keras.models import Model

inputs = Input(shape=(50,1))
lstm_layer = LSTM(10)(inputs)
x = Dense(10, activation='relu')(lstm_layer)
output = Dense(1, activation='sigmoid')(x)

model = Model(inputs=inputs, outputs=output)

## Subclassing API

In [29]:
import tensorflow as tf

In [30]:
class LinearRegression(tf.keras.Model):
  def __init__(self):
    super(LinearRegression, self).__init__()
    self.linear_layer = tf.keras.layers.Dense(1, input_dim=1, activation='linear')

  def call(self, x):
    y_pred = self.linear_layer(x)

    return y_pred

In [31]:
model = LinearRegression()
X = [1, 2, 3, 4, 5, 6, 7, 8, 9] # 공부하는 시간
y = [11, 22, 33, 44, 53, 66, 77, 87, 95] # 각 공부하는 시간에 맵핑되는 성적
sgd = tf.keras.optimizers.SGD(lr=0.01)
model.compile(optimizer=sgd, loss='mse', metrics=['mse'])
model.fit(X, y, epochs=300)

Epoch 1/300
1/1 [==============================] - 0s 141ms/step - loss: 3064.5515 - mse: 3064.5515
Epoch 2/300
1/1 [==============================] - 0s 3ms/step - loss: 378.0941 - mse: 378.0941
Epoch 3/300
1/1 [==============================] - 0s 4ms/step - loss: 47.5449 - mse: 47.5449
Epoch 4/300
1/1 [==============================] - 0s 3ms/step - loss: 6.8726 - mse: 6.8726
Epoch 5/300
1/1 [==============================] - 0s 3ms/step - loss: 1.8674 - mse: 1.8674
Epoch 6/300
1/1 [==============================] - 0s 4ms/step - loss: 1.2508 - mse: 1.2508
Epoch 7/300
1/1 [==============================] - 0s 4ms/step - loss: 1.1742 - mse: 1.1742
Epoch 8/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1640 - mse: 1.1640
Epoch 9/300
1/1 [==============================] - 0s 4ms/step - loss: 1.1620 - mse: 1.1620
Epoch 10/300
1/1 [==============================] - 0s 4ms/step - loss: 1.1610 - mse: 1.1610
Epoch 11/300
1/1 [==============================] - 0s 3ms/step -

1/1 [==============================] - 0s 3ms/step - loss: 1.1127 - mse: 1.1127
Epoch 90/300
1/1 [==============================] - 0s 4ms/step - loss: 1.1122 - mse: 1.1122
Epoch 91/300
1/1 [==============================] - 0s 2ms/step - loss: 1.1118 - mse: 1.1118
Epoch 92/300
1/1 [==============================] - 0s 2ms/step - loss: 1.1114 - mse: 1.1114
Epoch 93/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1109 - mse: 1.1109
Epoch 94/300
1/1 [==============================] - 0s 2ms/step - loss: 1.1105 - mse: 1.1105
Epoch 95/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1101 - mse: 1.1101
Epoch 96/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1097 - mse: 1.1097
Epoch 97/300
1/1 [==============================] - 0s 4ms/step - loss: 1.1093 - mse: 1.1093
Epoch 98/300
1/1 [==============================] - 0s 2ms/step - loss: 1.1089 - mse: 1.1089
Epoch 99/300
1/1 [==============================] - 0s 3ms/step - loss: 1.1085 - ms

1/1 [==============================] - 0s 3ms/step - loss: 1.0857 - mse: 1.0857
Epoch 177/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0855 - mse: 1.0855
Epoch 178/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0852 - mse: 1.0852
Epoch 179/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0850 - mse: 1.0850
Epoch 180/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0848 - mse: 1.0848
Epoch 181/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0846 - mse: 1.0846
Epoch 182/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0844 - mse: 1.0844
Epoch 183/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0842 - mse: 1.0842
Epoch 184/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0840 - mse: 1.0840
Epoch 185/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0838 - mse: 1.0838
Epoch 186/300
1/1 [==============================] - 0s 2ms/step - loss: 1

1/1 [==============================] - 0s 3ms/step - loss: 1.0725 - mse: 1.0725
Epoch 264/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0724 - mse: 1.0724
Epoch 265/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0723 - mse: 1.0723
Epoch 266/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0722 - mse: 1.0722
Epoch 267/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0721 - mse: 1.0721
Epoch 268/300
1/1 [==============================] - 0s 4ms/step - loss: 1.0720 - mse: 1.0720
Epoch 269/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0719 - mse: 1.0719
Epoch 270/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0718 - mse: 1.0718
Epoch 271/300
1/1 [==============================] - 0s 3ms/step - loss: 1.0717 - mse: 1.0717
Epoch 272/300
1/1 [==============================] - 0s 2ms/step - loss: 1.0716 - mse: 1.0716
Epoch 273/300
1/1 [==============================] - 0s 3ms/step - loss: 1

In [32]:
model.predict([9])

array([[96.865524]], dtype=float32)